### ISSUE TITLE
Config - extensions.command not handling spaces very well

### ISSUE THREAD

**Issue by Blatman** [neutralinojs/neutralinojs#824] opened 2022-03-08 17:33 UTC
Using the minimal sample and just running binary in same folder I'm getting path failures using the extensions.

neutralino.config.json -

    "extensions": [
        {
            "id": "js.neutralino.sampleextension",
            "command": "${NL_PATH}/extensions/sampleextension"

Found the "command" line to fail for volumes with spaces - in this case NL_PATH was /Volumes/LaCie SSD/....

the devtools console error was - /bin/sh: /Volumes/LaCie: No such file or directory

Was OK if I used "command": " /Volumes/LaCie\\ SSD/....
Using Global containing spaces is no good.

**Specifications**  
* NeutralinoJs Version: 4.3.0
* NeutralinoJs Client version: 3.2.0
* Platform: MacOS 10.13

**Comment by shalithasuranga** [comment] 2023-09-19 08:10
Hey.. Thanks for reporting this issue @Blatman, I think we can close this as a duplicate of #829 

Thanks :tada:

**Closed by shalithasuranga** 2023-09-19 08:10 UTC
