### ISSUE TITLE
App doesn't respond to clicks after un-hibernation

### ISSUE THREAD

**Issue by JustPilz** [neutralinojs/neutralinojs#1256] opened 2024-05-28 19:09 UTC
If an application is running and the computer is put into hibernation mode, the application stops responding to any clicks inside the window when it returns from hibernation mode, and it can't be closed using [this workaround](https://github.com/neutralinojs/neutralinojs/issues/1179). The only solution is to kill the application process through Task Manager. But the app didn't freeze: `cursor: "pointer"` works when hovering over the button.

**Steps to reproduce the behavior:**
1. Run application (after building, not dev-mode)
2. Click any button that you have. It's work.
3. Hibernate the device.
4. Un-hibernate the device.
5. Try to click the button again. Nothing happened.

**Expected behavior**
The button is pressed, the action is performed.

**Specifications**  
 - OS: Windows 10 Pro x64
 - Neutralinojs binaries: v5.0.0
 - Neutralinojs client: v5.0.0
 - neu CLI: v11.0.1

**Comment by shalithasuranga** [comment] 2024-05-29 11:22
Thanks so much for reporting this issue. Closing this as a duplicate of https://github.com/neutralinojs/neutralinojs/issues/970

**Closed by shalithasuranga** 2024-05-29 11:22 UTC
Labels: bug
