### ISSUE TITLE
Tray menu UnhandledPromiseRejectionWarning on 2.4.0

### ISSUE THREAD

**Issue by chief-nerd** [neutralinojs/neutralinojs#492] opened 2021-06-27 16:04 UTC
**Expected Behavior**  
Tray Icon appearing:
  
**Actual Behavior**  
UnhandledPromiseRejectionWarning

**Steps to Reproduce the Problem**  

index.html in /resources 
```html
<!doctype html>
<html lang="en">

<head>
	<meta charset="utf-8" />
	<script src="/resources/neutralino.js"></script>
</head>
<body>
        <script>
		Neutralino.init();
		try {
			Neutralino.os.setTray({
				icon: "/icons/appIcon.png",
			})
		} catch (ex) {
			console.error(ex);
		}
	</script>
</body>

</html>
```

neutralino.config.json
```json
{
  "applicationId": "js.neutralino.otray",
  "port": 0,
  "defaultMode": "window",
  "enableHTTPServer": true,
  "enableNativeAPI": true,
  "url": "/resources/",
  "nativeBlockList": [],
  "globalVariables": {},
  "modes": {
    "window": {
      //reducted
    },
    "browser": {},
    "cloud": {}
  },
  "cli": {
    "binaryName": "otray",
    "resourcesPath": "/resources/",
    "clientLibrary": "/resources/neutralino.js",
    "binaryVersion": "2.4.0",
    "clientVersion": "1.0.0"
  }
}
```

AppIcon attached
![appIcon](https://user-images.githubusercontent.com/9266151/123551432-067c8700-d772-11eb-8381-0dc9cce0f6d8.png)

**Specifications**  
* Neutralinojs binaries: v2.4.0
* Neutralinojs client: v1.0.0
* neu CLI: v5.1.2
* System Version:	macOS 11.2.1 (20D74)
* Kernel Version:	Darwin 20.3.0

**Comment by shalithasuranga** [comment] 2021-06-30 14:48
@chief-nerd  Could you check by creating a new app with the latest CLI version. I included tray-menu for all new apps.

**Comment by shalithasuranga** [comment] 2021-12-14 13:48
The latest version (v4) is tested on macOS. Therefore closing as a duplicate of https://github.com/neutralinojs/neutralinojs/issues/615 .. Thanks for reporting this.

**Closed by shalithasuranga** 2021-12-14 13:48 UTC
