### ISSUE TITLE
os.showOpenDialog window to background

### ISSUE THREAD

**Issue by rince1984** [neutralinojs/neutralinojs#715] opened 2021-12-05 11:03 UTC
**Expected Behavior**  
On ```Neutralino.os.showOpenDialog()``` the explorer window should be pop up in foreground (in front of) the app.
  
**Actual Behavior**  
The explorer window pops up behind the app.

**Steps to Reproduce the Problem**  
 Just use ```Neutralino.os.showOpenDialog()```. I have installed webview2, maybe its another behavior without webview2 (I can't test it).

**Specifications**  
* NeutralinoJs Version: Client version = v2.0.0 ; Binary version = v3.0.0
* NeutralinoJs CLI version: 7.0.0
* Platform: Win 10 (Home/Pro)

**Comment by mzy2240** [comment] 2021-12-05 15:50
How did u get the 3.0 version neutralinojs? It seems the latest is just 2.0 https://github.com/neutralinojs/neutralino.js

**Comment by rince1984** [comment] 2021-12-06 17:13
> How did u get the 3.0 version neutralinojs? It seems the latest is just 2.0 https://github.com/neutralinojs/neutralino.js

Client version: v2.0.0
Binary version: v3.0.0

**Comment by joshuakraitberg** [comment] 2021-12-11 03:56
This is a revert of #472 probably caused by #642.

**Comment by shalithasuranga** [comment] 2022-02-02 19:58
Hey.. all.. This issue was fixed. will be released with the next version. Thanks for reporting :)

**Closed by shalithasuranga** 2022-02-02 19:58 UTC
Labels: platform: Windows, API
