### ISSUE TITLE
Some questions regarding NeutralinoJS

### ISSUE THREAD

**Issue by dipenchand** [neutralinojs/neutralinojs#589] opened 2021-09-15 15:16 UTC
I followed https://github.com/neutralinojs/neutralinojs/issues/587#issuecomment-919812594
- I could just see the following output on browser, but not much details.
  ```
  {
    "needsReload": false,
    "success": true
  }
  ```
- Is there a way to get details output, when command executes?
- I have to run command `node server.js`, then how can I achieve this?
- And even I did some typos like `await Neussstralino.os.execCoasdfgmmand`, it always outputs `success: true`

_Originally posted by @dipenchand in https://github.com/neutralinojs/neutralinojs/issues/587#issuecomment-919862368_

**Comment by danisss9** [comment] 2021-10-01 13:12
The response you see is Neutralino pinging the server to check if you changed your code so it hot reloads. Its not the call you made with your code.

If you misspell the command it is probably not running the command but javascript wont say anything because thats how js works. 

I usually just console log the results of the calls and if it is "undefined" then you probably wrote something wrong.

**Comment by shalithasuranga** [comment] 2021-11-13 12:08
Hey.. Thanks for reporting and discussing this. I am closing this since the above problems are to reproducable with the latest version

**Closed by shalithasuranga** 2021-11-13 12:08 UTC
