### ISSUE TITLE
Run without opening terminal?

### ISSUE THREAD

**Issue by OmgImAlexis** [neutralinojs/neutralinojs#209] opened 2019-12-14 04:47 UTC
**Expected Behavior**  
App to open.
  
**Actual Behavior**  
Terminal window opens to run start script, then app shows.

**Steps to Reproduce the Problem**  
Double click `neutralino-mac`.

**Specifications**  
* NeutralinoJs Version: latest
* Platform: MacOS

**Comment by kasvith** [comment] 2019-12-22 04:40
Please package your application in an AppPackage. See example folder in mac

This behaviour is normal in OSX

**Comment by OmgImAlexis** [comment] 2019-12-22 07:07
Double clicking the app icon does the same thing.

**Comment by kasvith** [comment] 2019-12-22 08:04
check `core-macos/examples/Neut.app`

**Comment by kasvith** [comment] 2019-12-22 08:08
https://github.com/neutralinojs/neutralinojs/tree/master/core-macos/example contains this example. Please double click and you will see no terminal

**Comment by kasvith** [comment] 2019-12-29 04:54
@OmgImAlexis is the problem resolved?

**Comment by OmgImAlexis** [comment] 2019-12-29 06:04
I haven’t had a chance to check as I’m on break at the moment.

**Comment by Eflyax** [comment] 2020-04-07 10:27
I can confirm that it works. Terminal is not open.

macOs Catalina 10.15.1

**Comment by kasvith** [comment] 2020-04-07 11:28
Im closing issue

**Closed by kasvith** 2020-04-07 11:28 UTC
Labels: question

**Comment by hesselbom** [comment] 2021-06-04 08:58
@kasvith It seems like this has resurfaced and the example URL is now broken. Is there any way to open a compiled OSX app without opening terminal? I'm running macOS Big Sur (v11.4) on an Apple M1 chip if that helps.

Since it's my first comment I'd also like to add, great job on this project!

**Comment by shalithasuranga** [comment] 2021-06-04 13:42
Hey.. @hesselbom Thanks for checking Neutralinojs. You can still access the folder form: https://github.com/neutralinojs/neutralinojs/tree/v1.9.0/core-macos/example  The plan is to generate the same structure with CLI's  build command.

**Comment by hesselbom** [comment] 2021-06-14 08:22
@shalithasuranga Thanks for answering. I actually found out by mistake that with the current version of Neutralino, if I rename the mac bin in the dist folder from `{{binaryName}}-mac` to `{{binaryName}}-mac.app` I suddenly don't get a terminal when running the app. Maybe this is something the CLI could do automatically when building for release (as well as including app icons, maybe).
