### ISSUE TITLE
Bundle with server side languages

### ISSUE THREAD

**Issue by flip111** [neutralinojs/neutralinojs#151] opened 2019-03-19 23:32 UTC
neutralinojs comes with a C++ server. It's not clear to me what exactly is the server side doing. But i was wondering if it's possible to bundle neutralinojs with languages such as php, ruby, python and haskell and possibly some databases or other tools.

With electron i saw a view examples around such as this one https://codetalk.io/posts/2016-05-11-using-electron-with-haskell.html

**Comment by shalithasuranga** [comment] 2019-03-21 04:28
c++ server of neutralinojs is handling all backend calls such as filesystem access. terminal access etc (See [docs](https://neutralino.js.org/docs/#/) for more). 

The article you mentioned explains how electron app connects with a server which is written with Haskell. Also, that task is possible with neutralinojs too. So you can use [`os.runCommand`](https://neutralino.js.org/docs/#/api/os?id=osruncommandstring-command-function-successdata-function-error) to start the server and maybe JQuery to communicate with the server.

**Comment by flip111** [comment] 2019-03-21 11:17
Aah that's pretty great. Would be good to put that in a FAQ of some sorts :)

To which server would jQuery have to connect to? Some port on localhost? What if there are problems with the server like port already being in use?

**Comment by shalithasuranga** [comment] 2019-03-22 06:46
Yeah! this can be added to documentation. thanks!

Neutralino usually uses a random port for its server. So no need to know about that :) . But in this case there is another custom server. So, you can decide which port you are going to use

**Comment by telamon** [comment] 2019-08-20 10:35
@shalithasuranga Actually i recently tried the custom server approach. But i always ended up with a network error when i tried to communicate with my custom **local** backend, thus I assumed that it was not possible to make arbitrary requests.

But reading this issue maybe my assumptions are wrong? I couldn't find any tests or proof anywhere that this approach is supposed to work.

**Comment by kasvith** [comment] 2019-09-15 14:45
This can be done for sure, we can explicitly disable default API server and allow connecting to any backend as mentioned in the electron article

**Comment by telamon** [comment] 2019-09-15 19:55
@kasvith I can confirm that it works, the connection error i had was my own fault due to having once again accidentally confused which server should serve up the CORS header. Once a valid CORS header was added to my custom backend everything worked gloriously.

**Comment by shalithasuranga** [comment] 2021-01-21 13:54
Hey.. I am closing this issue because the question has been answered already..

**Closed by shalithasuranga** 2021-01-21 13:54 UTC
Labels: question
