### ISSUE TITLE
GLIBCXX_3.4.26 not found

### ISSUE THREAD

**Issue by lexesv** [neutralinojs/neutralinojs#371] opened 2021-02-16 17:56 UTC
Debian GNU/Linux 10 (buster)
Linux 5.7.0-0.bpo.2-amd64 #1 SMP Debian 5.7.10-1~bpo10+1 (2020-07-30) x86_64 GNU/Linux

./neutralino-linux: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by ./neutralino-linux)

**Comment by shalithasuranga** [comment] 2021-02-17 13:47
Hey.. did you try to compile Neutralino? or tried to run the binary file for Linux?

**Comment by lexesv** [comment] 2021-02-17 18:35
I tried to run the binary.
But now I compiled Neutralino for Linux.

**Comment by Efrainq07** [comment] 2021-04-22 18:02
I has this same issue on Ubuntu 18.04.
I solved it by running:
`sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get install gcc-4.9
sudo apt-get upgrade libstdc++6`

**Comment by shalithasuranga** [comment] 2021-08-01 09:36
Closing this since the solution is posted by @Efrainq07 . `libstdc++6` newer package is required and only older Linux distro versions have older versions of `libstdc`

**Comment by pkulijing** [comment] 2022-02-28 09:49
> Closing this since the solution is posted by @Efrainq07 . `libstdc++6`'s newer package version is required and only older Linux distro versions have older versions of `libstdc`

I wouldn't call this a solution because it's a dangerous action to update libstdc++ manually. Actually I'm not sure if it shall work: why is he using a very new version of libstdc++ and an outdated version of gcc together? Ubuntu 18.04 by default comes with gcc7.5 and glibcxx3.4.25 and reports this error. I think update the whole build-chain to gcc-9 (i.e. by updating build-essential, not just libstdc++) will solve the problem because it works fine in Ubuntu 18.04. But please note that Ubuntu 18.04 won't reach its end-of-life until 2028, and it's often not feasible to update the the whole build-chain in production environment (after all the ppa has a "test" in its name). So if neu cannot run in the default setting of ubuntu18.04, it's probable that a lot of potential user will be forced to find an alternative.

**Comment by pkulijing** [comment] 2022-02-28 10:18
Turns out it's just a compile environment issue as suggested in https://github.com/neutralinojs/neutralinojs/issues/711#issuecomment-1012227931
I too recompiled neutralinojs bin on ubuntu18 and it worked. So @shalithasuranga I think you'd better change the CI compile environment and use a lower version of gcc to fix the GLIBCXX error, as suggested by @msanguineti

**Comment by shalithasuranga** [comment] 2022-02-28 11:57
Thanks for checking this further @pkulijing .. I've reopened this issue to apply a fix for this issue :)

**Comment by shalithasuranga** [comment] 2022-04-20 11:28
Hey all.. Now the build workflow has been updated and tested with nightly builds on a VM. New binaries will be released with the next version and you all can use the `nightly` tag to get daily builds ;) Thanks for reporting and discussing this

**Closed by shalithasuranga** 2022-04-20 11:28 UTC
Labels: enhancement, question

**Comment by pkulijing** [comment] 2022-05-09 08:01
> 

I updated my config file with

```
    "binaryVersion": "4.5.0",
    "clientVersion": "3.4.0"
```

and now the problem is gone. Thanks!
