### ISSUE TITLE
filesystem.readDirectory fails when results would return filenames containing umlauts

### ISSUE THREAD

**Issue by sroauth** [neutralinojs/neutralinojs#782] opened 2022-01-30 18:16 UTC
**Expected Behavior**
Neutralino's native filesystem API should return a list of files when using the `readDirectory` method.
  
**Actual Behavior**
Neutralino is not returning anything when calling the `readDirectory` method.

**Steps to Reproduce the Problem**
 1. Have a file named `björn-kjellström.txt` in the directory being read from.
 2. Call the `readDirectory` method on the directory containing the file `björn-kjellström.txt`.

**Specifications**
* NeutralinoJs Version: 4.2.0
* NeutralinoJs CLI version: 3.1.0
* Platform: Windows 11 Pro 21H2

**Comment by DEVLOPRR** [comment] 2022-02-24 07:51
can you share the code too?

**Comment by rince1984** [comment] 2022-02-24 08:13
The problem occurs with all filesystem operations (e.g. ```copyFile```). I also need a solution for that.

**Comment by pathange-s** [comment] 2022-03-14 12:11
@rince1984 what error did you get when you tried to run any of the `filesystem` operations ?

I tried to call this function

```
function readDir() {
    Neutralino.filesystem.readDirectory('./')
    .then((result) => console.log(result))
    .catch((err) => console.log(err));
}
```
and obtained this as the output
```
[Log] Array (11) (main.js, line 20)
0 {entry: ".", type: "DIRECTORY"}
1 {entry: ".gitignore", type: "FILE"}
2 {entry: "LICENSE", type: "FILE"}
3 {entry: "bin", type: "DIRECTORY"}
4 {entry: ".tmp", type: "DIRECTORY"}
5 {entry: "neutralinojs.log", type: "FILE"}
6 {entry: "README.md", type: "FILE"}
7 {entry: "..", type: "DIRECTORY"}
8 {entry: "resources", type: "DIRECTORY"}
9 {entry: ".github", type: "DIRECTORY"}
10 {entry: "neutralino.config.json", type: "FILE"}
```
ie It worked as expected for me.


PS : If the same function was written as 

```
function readDir() {
    let entries = await Neutralino.filesystem.readDirectory(NL_PATH);
    console.log('Content: ', entries);
}
```

It threw these errors in the console.

```
[Error] SyntaxError: Unexpected identifier 'Neutralino'. Expected ';' after variable declaration.
	(anonymous function) (main.js:19)
[Error] ReferenceError: Can't find variable: createDir
	onclick (localhost:14)
```

This seems like a critical issue if its not functioning. @DEVLOPRR @shalithasuranga please look into the this comment.

**Comment by pathange-s** [comment] 2022-03-14 12:31
@rince1984 what error did you get when you tried to run any of the `filesystem` operations ?

I tried to call this function

```
function readDir() {
    Neutralino.filesystem.readDirectory('./')
    .then((result) => console.log(result))
    .catch((err) => console.log(err));
}
```
and obtained this as the output
```
[Log] Array (11) (main.js, line 20)
0 {entry: ".", type: "DIRECTORY"}
1 {entry: ".gitignore", type: "FILE"}
2 {entry: "LICENSE", type: "FILE"}
3 {entry: "bin", type: "DIRECTORY"}
4 {entry: ".tmp", type: "DIRECTORY"}
5 {entry: "neutralinojs.log", type: "FILE"}
6 {entry: "README.md", type: "FILE"}
7 {entry: "..", type: "DIRECTORY"}
8 {entry: "resources", type: "DIRECTORY"}
9 {entry: ".github", type: "DIRECTORY"}
10 {entry: "neutralino.config.json", type: "FILE"}
```
ie It worked as expected for me.


PS : If the same function was written as 

```
function readDir() {
    let entries = await Neutralino.filesystem.readDirectory(NL_PATH);
    console.log('Content: ', entries);
}
```

It threw these errors in the console.

```
[Error] SyntaxError: Unexpected identifier 'Neutralino'. Expected ';' after variable declaration.
	(anonymous function) (main.js:19)
[Error] ReferenceError: Can't find variable: createDir
	onclick (localhost:14)
```

Tested on :

- Ubuntu 20.04
- Windows 11

This seems like a critical issue if its not functioning. @DEVLOPRR @shalithasuranga please look into the this comment.

**Comment by rince1984** [comment] 2022-03-14 12:42
@pathange-s

For debugging I created following functions:

```
async function copyMyFile() {
	console.log('function copy start');
	let inFile = 'C:\\TEST\\Befehlsübersicht.txt';
	let outFile = NL_PATH + '/copied.txt';
	let cpInfo = await Neutralino.filesystem.copyFile(inFile, outFile);
	console.log('function copy end');
}

async function readMyDir(){
	console.log('function dir start');
	await Neutralino.filesystem.readDirectory('./')
    .then((result) => console.log('result:'+result))
    .catch((err) => console.log('err:'+err));
	console.log('function dir end');
}
```

In my app directory I have a file called ```Befehlsübersicht.txt```.

async function **readMyDir** writes only "function dir start" to console, nothing more. As a sync function (without await) it only writes "function dir start" and "function dir end" to console, without listing files and folders.

async function **copyMyFile** throws an error to console ```{"code":"NE_FS_COPYFER","message":"Cannot copy C:\\TEST\\Befehlsübersicht.txt to ./copied.txt"}```. Same if I try it as a sync function (without await).

If I rename my file from ```Befehlsübersicht.txt``` both functions work as expected (readMyDir and copyMyFile).

**Comment by DEVLOPRR** [comment] 2022-03-14 13:01
> async function copyMyFile throws an error to console {"code":"NE_FS_COPYFER","message":"Cannot copy C:\\TEST\\Befehlsübersicht.txt to ./copied.txt"}. Same if I try it as a sync function (without await).
> 
> If I rename my file from Befehlsübersicht.txt both functions work as expected (readMyDir and copyMyFile).

This is a issue we know, it's because of how neutralino treats text.
in GSOC 2022, they have [listed this](https://github.com/neutralinojs/gsoc2022#support-unicode-characters-in-neutralinojs-windows-version) and after GSOC 2022 starts we might get a fix to this.

**Comment by pathange-s** [comment] 2022-03-14 13:04
Oh, that means the issue is with the file naming ? Lol @DEVLOPRR ?

**Comment by kolbasa** [comment] 2022-04-03 15:09
The same applies to commands:
```js
await Neutralino.os.execCommand('echo "Döner"'); // never resolves
```

This bug should be prioritized. Frameworks without Unicode support are useless.

**Comment by pathange-s** [comment] 2022-04-03 19:53
Hey @kolbasa ! Agree with you to certain extent. The following issue is listed under GSoC ideas [here](https://github.com/neutralinojs/gsoc2022#support-unicode-characters-in-neutralinojs-windows-version). If not fixed during GSoC period, I am planning to pick this issue and solve it. Hope it get resolved soon.

**Comment by Dargalin** [comment] 2023-01-13 17:56
Hi. The problem with umlauts persists to this day.
Will there be a bug fix in the near future?

**Comment by shalithasuranga** [comment] 2023-05-13 07:22
Closing this since the Windows Unicode support was added via #1102. If a specific feature doesn't support Unicode still, I think we can create a separate issue. 

Thanks :tada:

**Closed by shalithasuranga** 2023-05-13 07:22 UTC
Labels: bug, platform: Windows
