### ISSUE TITLE
macOS- disable titlebar

### ISSUE THREAD

**Issue by Kees-van-Beilen** [neutralinojs/neutralinojs#1145] opened 2023-09-04 13:23 UTC
When creating a NSWindow on macOS you have the option of disabling the titlebar. This doesn't make your window behave as an borderless window but just as a window without titlebar (still allowing resize and such). Neutralino.js doesn't over this behaviour. 

I would like to see an option in the window config like "disableTitleBar" or something the like.

It could also be nice if the window pointer could be fetched by the javascript.  Which can call any native api to style the window to its needs.

**Comment by shalithasuranga** [comment] 2023-11-27 06:41
Closing as a duplicate of #509. Thanks so much for reporting this @Kees-van-Beilen :tada:

**Closed by shalithasuranga** 2023-11-27 06:41 UTC
Labels: feature-request
