### ISSUE TITLE
HMR is not working as expected on macOS

### ISSUE THREAD

**Issue by murshidazher** [neutralinojs/neutralinojs#376] opened 2021-02-22 09:50 UTC
**Expected Behavior**  
The browser/windows automatically detect changes and reload the window.
  
**Actual Behavior**  
The browser needs to be manually reloaded.

![Feb-22-2021 15-12-24](https://user-images.githubusercontent.com/22551211/108691045-0e58c000-7521-11eb-82a2-f34b441fabab.gif)

**Steps to Reproduce the Problem**  

***prerequisites***

```sh
> npm i -g @neutralinojs/neu
```
***steps***

> `yarn start` internally runs `neu listen --auto-build`

```sh
> git clone https://github.com/murshidazher/neutralinojs-react-typescript.git
> cd neutralinojs-react-typescript && yarn i
> neu build
> yarn start
```

**Specifications**  
* NeutralinoJs Version: v1.5
* NeutralinoJs CLI version: 2.3.1
* Platform: macOS Catalina v10.15.7

**Comment by shalithasuranga** [comment] 2021-02-22 13:24
Ah, the issue is that Neutralinojs's macOS version is still having the features of  v1.5.0.. Now the main version is v1.8.0 that consists of the support for the `listen` command's automatic reload. In other words, v1.5.0 doesn't support `NL_ARGS` that is used by this hot reload. I will close this one since we already have it on https://github.com/neutralinojs/neutralinojs/issues/310

Would be great if you could support us to add missing features for macOS. :heart:

**Closed by shalithasuranga** 2021-02-22 13:24 UTC
