### ISSUE TITLE
Add custom splash screen

### ISSUE THREAD

**Issue by murunwas** [neutralinojs/neutralinojs#845] opened 2022-03-27 14:33 UTC
Is it possible to create a splash screen to avoid the white box splash screen shown below??

**Expected Behavior**  
- [ ] Add your own splash screen
- [ ] Hide that white screen 
  
**Actual Behavior**  
![image](https://user-images.githubusercontent.com/8838943/160286414-321c5d4f-de48-47dd-a331-66e466e1494d.png)

**Comment by pathange-s** [comment] 2022-03-27 15:27
I think there is an issue raised for the same.
Check out [this issue](https://github.com/neutralinojs/roadmap/issues/5)
Hope this gets into action, soon !

**Comment by shalithasuranga** [comment] 2022-04-15 11:23
Thanks for reporting and discussing this. Closing this as a duplicate of https://github.com/neutralinojs/neutralinojs/issues/814

**Closed by shalithasuranga** 2022-04-15 11:23 UTC

**Comment by doaortu** [comment] 2024-06-02 03:51
for avoiding weird white flash screen, we can set the `window.transparent` to true in neutralino.config.json.
and It will show transparent window instead of white flash screen on first load.
`window.transparent` currently work on MacOS and Linux only (version.5.2.0)
