### ISSUE TITLE
App not launching MacOS High Sierra v10.13.6

### ISSUE THREAD

**Issue by kousiksatish** [neutralinojs/neutralinojs#318] opened 2020-10-01 13:49 UTC
**Actual Behavior**  
When I am trying to launch app in mac high sierra (10.13.6) after downloading the SDK, I get the following error:
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/kousiksatish/Downloads/neutralinojs-v1.5.0/./neutralino-mac (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/kousiksatish/Downloads/neutralinojs-v1.5.0/./neutralino-mac (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

[1]    2765 abort      ./neutralino-mac

**Expected Behavior**  
App should launch fine in all versions of MacOS.

Please let me know if anything can be done to work around this problem.

**Specifications**  
* NeutralinoJs Version: 1.5.0
* NeutralinoJs CLI version: 1.7.0
* Platform: MacOS High Sierra 10.13.6

**Comment by abulka** [comment] 2021-03-11 04:14
Also doesn't launch on Mac Mojave, neu 2.4.0.

Creating a release builds OK but running the dist/ app gives

```
$ ./dist/hello-world-release/hello-world-mac 
ERROR [/Users/codecey/Desktop/untitled folder/neutralinojs/core-macos/src/settings.cpp:getSettings] [json.exception.parse_error.101] parse error at 1: syntax error - unexpected end of input; expected '[', '{', or a literal
libc++abi.dylib: terminating with uncaught exception of type nlohmann::detail::type_error: [json.exception.type_error.302] type must be string, but is null
Abort trap: 6
```

some weird path `/Users/codecey/` from another machine seems to be the cause?

Someone else also complaining about this path in #328.

**Comment by shalithasuranga** [comment] 2021-03-11 12:52
Hey... Please notice that the macOS version is a bit behind compared to the Linux/Windows versions. https://github.com/neutralinojs/neutralinojs/issues/310 :)

**Comment by shalithasuranga** [comment] 2021-03-11 12:53
If you are interested in contributing really appreciate it:+1:

**Comment by shalithasuranga** [comment] 2021-05-25 15:01
Please check v2 release

**Comment by abulka** [comment] 2021-05-27 23:21
After updating neu to `@neutralinojs/neu@3.1.0` and re-running my hello-world app I now get a different error.

```
$ neu run
/Users/Andy/.nvm/versions/node/v12.18.3/lib/node_modules/@neutralinojs/neu/src/modules/runner.js:7
    let binaryName = settingsObj.cli.binaryName;
                                     ^

TypeError: Cannot read property 'binaryName' of undefined
    at Object.module.exports.runApp (/Users/Andy/.nvm/versions/node/v12.18.3/lib/node_modules/@neutralinojs/neu/src/modules/runner.js:7:38)
    at Command.<anonymous> (/Users/Andy/.nvm/versions/node/v12.18.3/lib/node_modules/@neutralinojs/neu/src/commands/run.js:8:20)
    at Command.listener (/Users/Andy/.nvm/versions/node/v12.18.3/lib/node_modules/@neutralinojs/neu/node_modules/commander/index.js:370:29)
    at Command.emit (events.js:315:20)
    at Command.parseArgs (/Users/Andy/.nvm/versions/node/v12.18.3/lib/node_modules/@neutralinojs/neu/node_modules/commander/index.js:892:12)
    at Command.parse (/Users/Andy/.nvm/versions/node/v12.18.3/lib/node_modules/@neutralinojs/neu/node_modules/commander/index.js:642:21)
    at Object.<anonymous> (/Users/Andy/.nvm/versions/node/v12.18.3/lib/node_modules/@neutralinojs/neu/bin/neu.js:10:9)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

P.S. For comparison, I built a brand new hello-world app (as per the project's readme `neu create hello-world`) and got the original error again, which is also happening to others #265

**Comment by shalithasuranga** [comment] 2021-05-28 08:36
@abulka  Hey.. looks like you are using an older version of config file format. Could you please create a new project with `neu create app-name` and check whether it works?

**Comment by abulka** [comment] 2021-05-28 12:59
@shalithasuranga I did create a brand new project, see the P.S in my post above and #265.

**Comment by abulka** [comment] 2021-05-28 23:20
@shalithasuranga you could probably close this issue since it works on High Sierra, which is the title of the issue. The fact that it doesn't run on Mojave is covered by the open issue #265.

**Comment by shalithasuranga** [comment] 2021-05-30 09:16
Yeah okay, thanks for checking @abulka I will check the issue with Mojave then :+1:

**Closed by shalithasuranga** 2021-05-30 09:16 UTC
