### ISSUE TITLE
linux build but can not use on Windows 10

### ISSUE THREAD

**Issue by passerbyo** [neutralinojs/neutralinojs#953] opened 2022-07-18 08:49 UTC
**Describe the bug**
linux build but can not use on Windows 10

**To Reproduce**
1. npm build on kali linux arm64
2. copy x64 exe into windows 10
3.click run

**Expected behavior**
linux build but can not use on Windows 10

**Screenshots/Screen recordings**
If applicable, add screenshots/screen recordings to help explain your problem.

**Specifications**  
 - OS: Windows 10 x64
 - Neutralinojs version: v4.3.0
 - Neutralinojs client library version:  v3.3.0
 - Neutralinojs CLI version: v9.1.2

*Note: you can enter the `neu version` command to find these details*

**Additional context**
no.

**Comment by pegvin** [comment] 2022-07-18 09:04
Can you specify the error you're getting?

**Comment by kolbasa** [comment] 2022-07-20 07:09
I had a similar problem. I had to install [Microsoft WebView2](https://developer.microsoft.com/de-de/microsoft-edge/webview2/) for it to work.
Maybe that helps.

**Comment by shalithasuranga** [comment] 2023-11-27 06:06
Closing as a duplicate of #959. Thanks for reporting and discussing :tada:

**Closed by shalithasuranga** 2023-11-27 06:06 UTC
Labels: bug
