### ISSUE TITLE
Bypass X-Frame-Options header

### ISSUE THREAD

**Issue by JASFramework** [neutralinojs/neutralinojs#559] opened 2021-08-16 15:20 UTC
**A way to bypass X-Frame-Options header with the config script**  
Due to clickjacking, websites can block the use of the iFrame tag where it does not work. In some cases, iFrames is a very useful tool that can't be replaced. Currently, a [Github project](https://github.com/niutech/x-frame-bypass) allows you to bypass the header, but it interferes with both the CSS and JS. 
  
**This feature does not exist so there is no "Actual Behavior"**  

**Specifications**  

**--- Global ---**
Neutralinojs binaries: v2.6.0
Neutralinojs client: v1.3.0
neu CLI: v6.0.3

* Platform: [Parrot OS/Linux]

**Comment by shalithasuranga** [comment] 2021-12-09 18:16
Thanks for reporting this. Closing as a duplicate of https://github.com/neutralinojs/neutralinojs/issues/586

**Closed by shalithasuranga** 2021-12-09 18:16 UTC
Labels: duplicate
