### ISSUE TITLE
Can't close app immediately on windows11

### ISSUE THREAD

**Issue by easyfrog** [neutralinojs/neutralinojs#1221] opened 2024-03-13 11:31 UTC
**Describe the bug**
app window is Freezed when click close button on windows11

**To Reproduce**
1. create a template app on windows
2. run it
3. click the close button on the right top

**Expected behavior**
when user click `close` button, the app will close immediately.

**Screenshots/Screen recordings**
![动画](https://github.com/neutralinojs/neutralinojs/assets/10724325/4f87f520-85b8-4276-a44a-f9902368cdad)

**Specifications**  
 - OS: window11 23H2
- neu CLI: v11.0.1
- Project: neutralinojs-zero (js.neutralino.zero)
- Neutralinojs binaries: v5.0.0
- Neutralinojs client: v5.0.1
- Project version: v1.0.0

**Comment by JustPilz** [comment] 2024-03-16 21:28
Duplicate of https://github.com/neutralinojs/neutralinojs/issues/1179

**Closed** 2024-03-17 13:20 UTC
Labels: bug
