### ISSUE TITLE
Loading local images without base64

### ISSUE THREAD

**Issue by stephanbogner** [neutralinojs/neutralinojs#1033] opened 2022-11-21 10:20 UTC
**Is your feature request related to a problem? Please describe.**
I want to show images that are located somewhere on the computer (= not in e.g. /react/public/). Basically the same use case a photo viewer app for local images has.

**Describe the solution you'd like**
Allowing local files, e.g. `<img src="file://home/stephan/Desktop/SomeFolder/DSCF1039.JPG" alt="ABC"/>`.
I think basically how [Electron handles it with `webSecurity: false`](https://github.com/electron/electron/issues/23757#issuecomment-640146333).

**Describe alternatives you've considered**
I am using `readBinaryFile` and then convert the arrayBuffer to a base64 string using custom code. Unfortunately the performance is pretty bad when handling large images (i.e. 15mb).

**Comment by crackheadakira** [comment] 2022-11-22 16:28
This feature is also something I wish for, as currently I'm trying to make a music player with Neutralino and it'd be so much easier to link the covers and audio files.

**Comment by stephanbogner** [comment] 2022-11-23 01:56
> This feature is also something I wish for, as currently I'm trying to make a music player with Neutralino and it'd be so much easier to link the covers and audio files.

Yeah, my last idea was to use a webworker for the conversion to base64 so it doesn't block the UI.
It did bring quite an improvement but not to the extent that it was acceptable performance.

I now had to port my app to Tauri and the performance of loading images is perfect. I don't like Tauri yet as much as Neutralino ... but I didn't see any other solution here :cry:

**Comment by Antix-Development** [comment] 2022-11-27 17:12
Not being able to load local files seems to be an issue that has been around since this frameworks inception and repeatedly raised as issues, and with no actual result except "use base64".

I'm creating a TexturePacker like app and that's really not acceptable.

I hope this framework one day does manage to support local file loading, until then it's back to bloaty old Electron which can at least load local files without any headaches.

**Comment by system32uwu** [comment] 2023-06-16 21:20
https://github.com/neutralinojs/neutralinojs/blob/main/bin/extensions/sampleextension/main.js

why rely on the sole maintainer when you can add the feature yourself? you can use fs from node and send the data with extensions through *websockets*

```
{
  filename: 'myfile',
  format: 'txt',
  data: '...'
}
```

not that hard

**Comment by shalithasuranga** [comment] 2023-11-25 12:33
Closing as a duplicate of #993 and #586. Thanks for reporting this issue :tada:

**Closed by shalithasuranga** 2023-11-25 12:33 UTC
Labels: feature-request

**Comment by rince1984** [comment] 2023-12-16 10:43
> https://github.com/neutralinojs/neutralinojs/blob/main/bin/extensions/sampleextension/main.js
> 
> why rely on the sole maintainer when you can add the feature yourself? you can use fs from node and send the data with extensions through _websockets_
> 
> ```
> {
>   filename: 'myfile',
>   format: 'txt',
>   data: '...'
> }
> ```
> 
> not that hard

You are right that it is relatively easy to create an extension for this. But firstly, such a functionality should be seen as standard and secondly, with a Node extension you also have to include NodeJS, which results in an unnecessarily bloated app size. ;)

**Comment by rince1984** [comment] 2023-12-16 11:01
@shalithasuranga sorry for my stupid question, but is this feature released in v4.15? I cannot find any hint on that...

**Comment by hschneider** [comment] 2023-12-16 12:57
You can use one of the NodeJS capable extensions for this:

https://github.com/hschneider/neutralino-ext-bun
https://github.com/hschneider/neutralino-ext-node

**Comment by rince1984** [comment] 2023-12-16 13:53
> You can use one of the NodeJS capable extensions for this:
> 
> https://github.com/hschneider/neutralino-ext-bun https://github.com/hschneider/neutralino-ext-node

Thanks for sharing, but that is not a solution, it is a workaround to fill a missing standard functionallity. Like many others I think using local files directly is one of the most important "features" we need in NeutralinoJS without an extension. I create productive tools where I need to show a lot of preview images. I have implemented a workaround that works fine without an extension with further dependencies, but for new apps I would appreciate to have that functionallity within NeutralinoJS. 
Because shalita closed all issues to this topic and set it to the next milestone (the already released version 4.15), I thought it is implemented without mentioning it in the release notes...

**Comment by hschneider** [comment] 2023-12-16 16:02
I see. What about filesystem.readBinaryFile() ?

**Comment by rince1984** [comment] 2023-12-16 16:20
That is possible but if you have a large number of images to view and/or these images are not that small it can cause a bad user experience and sometimes it crashes. Keep the images where they are and give access to them must be possible in a framework which is made to create desktop apps.
