### ISSUE TITLE
Don't show additional windows when app starts

### ISSUE THREAD

**Issue by JustPilz** [neutralinojs/neutralinojs#900] opened 2022-05-22 14:36 UTC
When you start the application (before the main window appears), several additional windows appear. Is it possible not to display them?  Also in this case the main window loses focus.

https://user-images.githubusercontent.com/24465747/169700598-9644db08-113d-4918-8421-f18f08156f8f.mp4

**Comment by pathange-s** [comment] 2022-05-22 18:40
On Windows right ? Opens smoothly on Linux (Ubuntu  20.04).

**Comment by JustPilz** [comment] 2022-05-22 19:02
> On Windows right ? Opens smoothly on Linux (Ubuntu 20.04).

Yes, it's Windows 10

**Comment by pathange-s** [comment] 2022-05-22 19:41
Cool. Will get back on this, once I test it on Windows.

**Comment by kodaloid** [comment] 2022-06-17 09:19
As talked about on Discord a few days ago, I suspect the cause is that `ShowWindow(m_window, SW_SHOW);` is called in [webview.h#L1288](https://github.com/neutralinojs/neutralinojs/blob/a5d8f3ffc516fc914da90fdcec27f19bbc4c1990/lib/webview/webview.h#L1288) 

Then later after the config is loaded, `ShowWindow(m_window, SW_HIDE);` is called in [window.cpp#L166](https://github.com/neutralinojs/neutralinojs/blob/a5d8f3ffc516fc914da90fdcec27f19bbc4c1990/api/window/window.cpp#L166)  to hide the shown window if `hidden` is set to `true`.

An idea to fix this could be to remove like 1288 (and maybe 1289,1290) from webview.h then in window.h around line 345 we could add an else statement that looks like this:

```
if(windowProps.hidden)
   window::hide();
else
   window::show();
```

That way if the window needs to be shown, it's done when the config is loaded.

Koda

**Comment by 6ixfalls** [comment] 2022-09-18 22:52
Hey @kodaloid, any updates on that fork of yours? If not I'll try fixing it myself and making a PR.

**Comment by kodaloid** [comment] 2022-09-19 00:36
My PR is still in submission phase, but was told on Discord that there's a good chance it'll get merged soon, so best to hold on and see what happens.

**Comment by shalithasuranga** [comment] 2023-07-18 10:16
Closing this since this issue was fixed in newer Neutralinojs versions, thanks all for discussing about this :tada:

**Closed by shalithasuranga** 2023-07-18 10:16 UTC
Labels: bug, module: Webview
