### ISSUE TITLE
User Agent

### ISSUE THREAD

**Issue by tizi24** [neutralinojs/neutralinojs#461] opened 2021-05-27 22:09 UTC
Hello, I have a query, can the User Agent be modified?

**Comment by shalithasuranga** [comment] 2022-01-03 12:52
Thanks for reporting this issue. We need to add it to the window mode - but it's already possible in Chrome mode via `modes.chrome.args`. Closing as a duplicate of https://github.com/neutralinojs/neutralinojs/issues/396

**Closed by shalithasuranga** 2022-01-03 12:52 UTC
