### ISSUE TITLE
UTF-8 not supported in Native API

### ISSUE THREAD

**Issue by ghost** [neutralinojs/neutralinojs#613] opened 2021-09-24 18:20 UTC
**Expected Behavior**  
Support cyrillic encoding in window title and filesystem.
  
**Actual Behavior**
Window title is not displayed correctly. Created directory is also corrupted.
![image](https://user-images.githubusercontent.com/55308117/134721940-2588bb6a-3f55-48a2-ab9e-260eaea62cb8.png)

**Steps to Reproduce the Problem**  
 1. Set `modes.window.title` to `Пример`
 2. Change `main.js` content to 
 ```
window.myApp = {
    showInfo: () => {
        Neutralino.filesystem.createDirectory({
            path: './папка',
        });
    },
    onWindowClose: () => {
        Neutralino.app.exit();
    }
};

Neutralino.init();
Neutralino.events.on("windowClose", myApp.onWindowClose);
window.myApp.showInfo();
```
 3. `neu run`

**Specifications**  
* Neutralinojs binaries: v2.8.0
* Neutralinojs client: v1.5.0
* neu CLI: v6.2.0
* Platform: Windows 10

**Comment by LTVA1** [comment] 2021-12-15 14:49
I have this problem too.

**Comment by khushit-shah** [comment] 2022-04-02 05:17
I was not able to reproduce it on windows 10 21H2

![image](https://user-images.githubusercontent.com/42430171/161367600-1e2dc989-6ec7-418b-a7f1-57eeba2f8700.png)

But the folder was not created, maybe I am missing some permissions in the config file.

**Comment by ebukaodini** [comment] 2022-04-19 16:43
I intend to work on this issue in the [GSoC 2022 Program](https://github.com/neutralinojs/gsoc2022#2-support-unicode-characters-in-neutralinojs-windows-version).

I'd appreciate every form of support in terms of screenshots of the bug.
Anything at all that would help me replicate and fix the bug.

Thanks.

**Comment by duzc2** [comment] 2022-05-25 20:23
i have this too
--- Global ---
neu CLI: v9.3.0

--- Project: OpenBlock (js.neutralino.sample) ---
Neutralinojs binaries: v4.5.0
Neutralinojs client: v3.4.0
Project version: v1.0.0

**Comment by pegvin** [comment] 2022-05-25 20:41
Sorry but unicode isn't currently supported, but is being worked on.

**Comment by duzc2** [comment] 2022-05-26 07:38
also does not support utf-8 in request url:

http://localhost:63507/project/assets/%E5%8F%A3%E5%8F%B7.png

**Comment by pegvin** [comment] 2022-05-26 11:32
yes we know that, sorry for the inconvenience.

**Comment by duzc2** [comment] 2022-05-27 04:50
OMG
I can't put the exe in a path with Chinese or any other utf-8 char

C:\Users\Administrator\Downloads\连线样例\proj_1\neujs-win_x64.exe

this make program crash.

hope u could fix this soon.

thank you.

**Comment by Hunlongyu** [comment] 2022-06-16 07:18
Hasn't it been solved yet?
This is very important. The name and title of the software cannot be in Chinese

**Comment by chenbimo** [comment] 2022-08-14 01:22
i have this problem too.

**Comment by Jarda-H** [comment] 2023-02-01 17:26
Same issue here :/
![image](https://user-images.githubusercontent.com/62809719/216116844-aab93157-bf44-411d-b4cb-ca4c2a07fc69.png)

Operating system name: Windows
Mode of the application: window
Neutralinojs framework version: 4.9.0
Neutralinojs client version: 3.8.0
Command-line arguments: bin\neutralino-win_x64.exe,,--load-dir-res,--path=.,--export-auth-info,--neu-dev-extension,--neu-dev-auto-reload

**Comment by shalithasuranga** [comment] 2023-05-13 07:22
Closing this since the Windows Unicode support was added via #1102. If a specific feature doesn't support Unicode still, I think we can create a separate issue. 

Thanks :tada:

**Closed by shalithasuranga** 2023-05-13 07:22 UTC
Labels: platform: Windows

**Comment by loopingstar** [comment] 2024-04-29 08:24
I have this problem too with french named (with accented characters) files and folders on window 10, with filesystem.readDirectory() and all other FS methods.
Thanks.
