### ISSUE TITLE
javascript error

### ISSUE THREAD

**Issue by zafalija** [neutralinojs/neutralinojs#192] opened 2019-10-25 13:07 UTC
**Actual Behavior**  
Neutralino prints two javascript errors:
1) expected identifier on line 1, character 945 in neutralino.js
2) neutralino not defined in app.js

**Specifications**  
* NeutralinoJs Version: v 1.2.0
* Platform: Windows 7

**Comment by psiservices-justin-sullard** [comment] 2020-09-03 00:26
I encountered this issue yesterday while getting started, so hopefully my experience can clarify what might be going on with your issue.

Through experimentation I have found that having you need to have `app/assets/neutralino.js` setup, but in `app/index.html` you needs to include it as `src="/neutralino.js"`.

The internal server sees the `app/assets/neutralino.js` and appends it to it's own generated set of defined constants, `NL_VERSION` etc. The appended variables are NOT set unless you include from `/neutralino.js` path, and do appear to be requested from the `neutralino.js` provided by the `neu` template.

It is highly recommend you use the `@neutralinojs/neu` package in your devDependencies and use the `neu create` command to get an app scaffolding (see <https://neutralino.js.org/docs/#/gettingstarted/quickstart> for instructions).

I also noticed that ALL assets referenced must be in the `app/assets` folder and referenced with `/assets/*` from within the HTML. I was not able to get anything but a JSON response for any assets at other paths.

**Comment by shalithasuranga** [comment] 2021-01-21 14:10
I am closing this since the issue is not present in the latest versions + neu-cli

**Closed by shalithasuranga** 2021-01-21 14:10 UTC
Labels: bug
