### ISSUE TITLE
Neutralino with vitejs and lit

### ISSUE THREAD

**Issue by boguz** [neutralinojs/neutralinojs#1004] opened 2022-10-09 15:27 UTC
**Describe the bug**
I am trying to create a neutralinojs app using vite and lit for the frontend.
I have followed the steps from the "[Using frontend libraries"](https://neutralino.js.org/docs/how-to/use-a-frontend-library) on the docs, but it doesn't seem to work.
- I can create and run the neutralinojs app. 😄 
- I can create, build and run the vite app. 😄 
- But i can't configure the neutralino app to run the vite app / frontend 💣 

**To Reproduce**
1. Create neutralino app with `neu create myapp --template neutralinojs/neutralinojs-zero`
2. cd into "myapp"
3. Create vite app (using lit and typescript) with `npm create vite@latest` (let say the app name is "my-lit-app")
4. delete the "www" folder
5. on neutralino-config-json change:
   5.1: `"documentRoot": "/my-lit-app/dist/"`
   5.2: `"icon": "/my-lit-app/dist/vite.svg"`
   5.3: `"resourcesPath": "/my-lit-app/dist/"`
   5.4: `"clientLibrary": "/my-lit-app/dist/my-lit-app.js"`
6. run `neu update` on the myapp folder
7. cd into "my-lit-app" and run `npm run install && npm run build`
8. run `neu run` back on the "myapp" folder
9. We get the error: "neutralino-mac_x64 quit unexpectedly." (see screenshot)

**Expected behavior**
I would love to use the vite lit app for the front end, but i can't understand how to configure it.
The vite app entry point is `my-li-app/index.html`, not sure if we should add this somewhere in the configuration

**Screenshots/Screen recordings**
- Screenshot of the alert box:
![image](https://user-images.githubusercontent.com/15846102/194765058-ac8b6a20-43e0-44dc-8c57-846cea98f6ed.png)

- on the console i get:
```
neu: INFO Starting process: neutralino-mac_x64  --load-dir-res --path=. --export-auth-info --neu-dev-extension --neu-dev-auto-reload
INFO 2022-10-09 17:20:45,741 Auth info was exported to ./.tmp/auth_info.json api/debug/debug.cpp:14 myname@unknown-host
neu: INFO neutralino-mac_x64 was stopped with success code 0
```

**Specifications**  
- OS: MacOS Monterey 12.4
- neu CLI: v9.3.1
- Neutralinojs binaries: v4.7.0
- Neutralinojs client: v3.6.0
- Project version: v1.0.0

**Comment by BeyondMagic** [comment] 2022-10-17 09:46
I do reproduce the same error on Arch Linux, however the client does not crash.

**CLIENT**
```Could not connect: Connection refused```

**CLI**
```
neu: INFO Starting process: neutralino-linux_x64  --load-dir-res --path=. --export-auth-info --neu-dev-extension  --url=http://localhost:12345
INFO 2022-10-17 06:44:28,189 Auth info was exported to ./.tmp/auth_info.json api/debug/debug.cpp:14 spirit@unknown-host
```

**Comment by cyrusbowman** [comment] 2023-04-03 02:34
@boguz the svg icon is the issue. Use the default icon.png from www, move it somewhere before you delete the directory.

If you are going to run vite during development you need to configure it to use a specific port and include that in neu config
```
"cli": {
...
    "frontendLibrary": {
        "patchFile": "/my-lit-app/index.html",
        "devUrl": "http://localhost:5678"
    }
}
```

then configure vite to match that port in `vite.config.js`:
```
export default defineConfig({
  server: {
    port: 5678,
    strictPort: true
  }
})
```

**Comment by boguz** [comment] 2023-04-11 11:55
Thank you. i will try it the next time i use Neutralino

**Comment by shalithasuranga** [comment] 2023-11-22 07:38
Closing this issue since it's already answered. Thanks for discussing :tada:

**Closed by shalithasuranga** 2023-11-22 07:38 UTC
Labels: bug
