### ISSUE TITLE
The promise-object from filesystem.readDirectory never resolves/rejects if a folder contains a file with scandinavian characters in its name

### ISSUE THREAD

**Issue by Majura-fi** [neutralinojs/neutralinojs#694] opened 2021-11-14 10:57 UTC
**Expected Behavior**  
The promise-object from `Neutralino.filesystem.readDirectory(...)` should resolve and return list of files or reject and return an error when a folder contains a file with scandinavian characters in its name.
![image](https://user-images.githubusercontent.com/12672127/141677754-f6306d55-b313-4ca4-bcca-01bf68b57fcc.png)
  
**Actual Behavior**
The promise-object from `Neutralino.filesystem.readDirectory(...)` will never resolve or reject when a folder contains a file with scandinavian characters in its name. No error messages are produced at all and promise will never be resolved or rejected.
![image](https://user-images.githubusercontent.com/12672127/141677737-3253d2ae-b44d-4733-bde8-3c9b44180a9b.png)
![image](https://user-images.githubusercontent.com/12672127/141677857-5a4da6ca-ae02-4a88-8daa-db95427617bb.png)

**Steps to Reproduce the Problem**  
 1. Download example project from https://github.com/Majura-fi/NeutralinoJS-ReadDirectoryBug
 2. Run `neu update` to download binaries in order to get the project up and running.
 2. Update line 8 in `NeutralinoJS-ReadDirectoryBug\resources\js\main.js` to point to the `testFile` folder inside the repository directory.
 3. Run the app with `neu run --arch=x64`
 4. Check the window's developer-console. Only one console message is shown. No errors are generated in window's developer-console or at terminal.

**Specifications**
* NeutralinoJs Version: binaries: v3.0.0 // client: v2.0.0
* NeutralinoJs CLI version: v7.0.1
* Platform: Windows 10 Home 64-bit (10.0, Build 18363)

**Comment by hv6erT** [comment] 2022-03-20 19:45
#782 Possible, it is the same issue

**Comment by shalithasuranga** [comment] 2023-05-15 12:51
I am closing this since Unicode support was added to the Windows version of Neutralinojs. Thanks :)

**Closed by shalithasuranga** 2023-05-15 12:51 UTC

**Comment by loopingstar** [comment] 2024-04-27 17:28
Hello, i have the same problem with french accented characters or special characters on folders names with Version 5.1.0 on Windows 10 pro

**Comment by hschneider** [comment] 2024-04-27 17:49
Looks like a duplicate of https://github.com/neutralinojs/neutralinojs/issues/1225
