### ISSUE TITLE
Binary crashes at startup in Windows Server 2019

### ISSUE THREAD

**Issue by IvoPereira** [neutralinojs/neutralinojs#610] opened 2021-09-23 21:39 UTC
**Expected Behavior**  
The binary application should run flawlessly in Windows Server 2019
  
**Actual Behavior**  
I have built the binaries on Linux.

Once opened (being an Administrator and without being an Administrator), just freezes as the following:

![image](https://user-images.githubusercontent.com/1396475/134587349-9f03102b-a52e-44e9-ba59-a18d29077e78.png)

Seems to be similar to the issue mentioned in https://github.com/neutralinojs/neutralinojs/issues/475 regarding an unexpected error on Windows Server.

I have tried to insert some logs along the code but it doesn't seem to register anything unless it is run on development mode in Linux. If you can provide me some debugging instructions I can get you more information.

**Steps to Reproduce the Problem**  
 1. Run Windows Server 2019 (for instance in a VM)
 2. Execute the Windows binary generated from NeutralinoJS
 3. Application crashes

**Specifications**  
* Neutralinojs binaries: v2.7.0
* Neutralinojs client: v1.4.0
* neu CLI: v6.1.1
* Platform: Windows Server 2019

**Comment by danidre14** [comment] 2021-09-23 22:43
Hi,

The latest build version is the v2.8.0 binary with a v1.5.0 client.

Try upgrading (neu update) to that version, and if it doesn't update, you may have to reinstall the global CLI.

No idea if this will solve the issue, but I am just suggesting it in hopes that it helps.

**Comment by IvoPereira** [comment] 2021-09-24 08:23
Thanks for the tip @danidre14.

I have just updated and reinstalled the global CLI.

Unfortunately it still freezes.

**Comment by IvoPereira** [comment] 2021-09-25 21:21
@shalithasuranga any debugging steps you can provide to help debugging this?

**Comment by shalithasuranga** [comment] 2021-09-26 05:51
Hey.. I think we can identify the root cause for this with the following actions.

- Check the binary for Windows in both ways: As a dev with neu CLI and as a user directly getting the released zip file. If it works as a dev, then there is a problem with bundling.
- Try installing webview2 runtime. If it works, there is a problem in the Edge library or our webview dependency. 
- Is there something inside `neutralino.log`? and you ran [this](https://neutralino.js.org/docs/getting-started/your-first-neutralinojs-app#step-1-creating-a-new-app) command with admin privileges on the command prompt?

**Comment by IvoPereira** [comment] 2021-09-26 10:14
Thanks a lot for the debugging steps.

Exactly, the issue is indeed the webview2 runtime. Once I have installed I was able to run a new application (and the one I was testing) perfectly.

Is there anything I can do to make the installation process automated for Webview2 runtime @shalithasuranga?

**Comment by rince1984** [comment] 2022-02-07 07:35
```Is there anything I can do to make the installation process automated for Webview2 runtime?

An answer to that question would be very helpful.

**Comment by rodryquintero** [comment] 2022-07-23 23:45
Had the same issue with an error message saying that the application was not compatible and gave me the option to close it. After manually installing the evergreen Webview2 installer, the problem was solved.

OS: *Windows Server 2016*

[WebView2 Installer](https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section
)

I guess we can always include the WebView installer along with the builds.

**Comment by shalithasuranga** [comment] 2023-11-25 11:38
Closing this since the issue is already answered (instaling the WebView2 runtime). Thanks for discussing this :tada:

**Closed by shalithasuranga** 2023-11-25 11:38 UTC
