### ISSUE TITLE
Sample app terminates

### ISSUE THREAD

**Issue by loveencounterflow** [neutralinojs/neutralinojs#523] opened 2021-07-17 10:49 UTC
**Expected Behavior**  
Expected the app to show a window
  
**Actual Behavior**  
`neu run` prints `Application was terminated.`

**Steps to Reproduce the Problem**  

```bash
pnpm install -g @neutralinojs/neu
neu create app-demo
cd app-demo
neu run
```

**Specifications**  
* NeutralinoJs Version: @neutralinojs/neu 5.1.5
* Platform: Linux Mint

**Comment by calderaro** [comment] 2021-07-25 20:02
i have this problem on macOS Big Sur 11.5 also

**Comment by rushsteve1** [comment] 2021-07-27 11:23
Same issue on OpenSUSE Tumbleweed and `@neutralinojs/neu@5.3.1`

**Comment by TobyWoodman** [comment] 2021-08-07 14:51
When can this be solved tho? I got the same problem on macOS Big Sur 11.4

**Comment by mallocator** [comment] 2021-08-09 17:26
I actually managed to get it to run by commenting out the ```window.myApp.setTray()``` call in the sample app in ```resources > js > main.js``` on line 55. Until this is fixed this may work as a workaround for you as well.

**Comment by shalithasuranga** [comment] 2021-08-09 17:45
Hey.. all. I think you all can find the reason for the launching issue with @neutralinojs/neu@6.0.3. It has new versions of both server and client. Once you run `neu run` it will show the actual command that gonna be executed. So you can run the command manually on the terminal to identify the issue similar to @rushsteve1's comment. 

Also, please note that the app indicator library is required to have the tray menu.

**Comment by topcheese** [comment] 2021-08-16 17:28
Is this related to some of the other issues on the Mac?  I'm using Mojave, and trying to run the demo app causes it to stop.  It pops up a window, then it show an error report.

**Comment by eeropic** [comment] 2021-08-19 14:27
Same on OSX 10.15.7
`./bin/neutralino-mac_x64  --load-dir-res --path=. --debug-mode`
results in 
`Segmentation fault: 11`

**Comment by tukusejssirs** [comment] 2022-06-17 22:21
The app app (installed either using `neu create app-name` or `neu create app-name --template neutralinojs/neutralinojs-zero`) terminates on Arch Linux too.

Running `./bin/neutralino-linux_x64 --load-dir-res --path=. --debug-mode` also results in segfault.

Commenting out [`resources/js/main.js` (L35)](https://github.com/neutralinojs/neutralinojs-minimal/blob/0ccb388767b7bf55baee517ba2ab82eb73bf520c/resources/js/main.js#L35) didn’t help.

I even installed a Svelte app, configured `neu` to use it based on [this](https://neutralino.js.org/docs/how-to/use-a-frontend-library/), but even that didn’t help.

All I can see is to open a window with dark grey background (not white/light, however, I use dark themes everywhere) for a fraction of a second, then it closes.

`neu run` outputs this:

```bash
neu: INFO Starting process: neutralino-linux_x64  --load-dir-res --path=. --export-auth-info --neu-dev-extension --neu-dev-auto-reload
INFO 2022-06-18 00:14:48,235 Auth info was exported to ./.tmp/auth_info.json api/debug/debug.cpp:14 ts@unknown-host
neu: INFO neutralino-linux_x64 was stopped with success code 0
```

**Comment by shalithasuranga** [comment] 2023-11-25 11:29
Closing this since the root cause is already reported in #615. Thanks for discussing :tada:

**Closed by shalithasuranga** 2023-11-25 11:29 UTC
Labels: question
