### ISSUE TITLE
Keyboard shortcuts does not work in window mode

### ISSUE THREAD

**Issue by chiptoe** [neutralinojs/neutralinojs#712] opened 2021-11-28 21:35 UTC
**Expected Behavior**  
Shortcuts cmd+[some key] should work in window mode.
When I start app in browser mode, shortcuts work.

**Actual Behavior**  
Shortcuts cmd+[some key] are blocked in window mode.

**Steps to Reproduce the Problem**  
 1. Create app with textarea and start it in window mode
 2. Try to copy/paste text

**Specifications**  
* NeutralinoJs Version: v3.0.0
* NeutralinoJs CLI version: v2.0.0
* Platform: macOS Big Sur v11.6

**Comment by shalithasuranga** [comment] 2021-12-07 18:20
Hey.. Thanks for reporting this I am closing this as a duplicate of https://github.com/neutralinojs/neutralinojs/issues/219

**Closed by shalithasuranga** 2021-12-07 18:20 UTC
Labels: platform: Darwin, module: Webview
