### ISSUE TITLE
Display Window Flashes Although Hidden: true

### ISSUE THREAD

**Issue by danidre14** [neutralinojs/neutralinojs#930] opened 2022-06-13 17:23 UTC
**Describe the bug**
When you launch a Neu application (either `neu run` or double clicking the `.exe` after a `neu build`), even though in the config `"hidden": true`, the window flashes on screen for 1 second then disappears, causing unexpected behaviour.

**To Reproduce**

1. Go to `neutralino.config.json`

2. Set `"hidden": true`
![example_hidden_true](https://i.imgur.com/nS3svWa.png)

3. Go to `resources/js/main.js`

4. Add code to bottom of file under `Neutralino.init` to show window after 2 seconds:
```js
setInterval(()=>Neutralino.window.show(),2000);
```
![example_show_window](https://i.imgur.com/mAEK9Cb.png)

5. Run application (with `neu run` or executable)

6. See error

**Expected behavior**
The app should begin, then two seconds later, the window should appear.

**Resulting behavior**
The app window flashes on screen, then vanishes, then two seconds later, appears once more.

**Screenshots/Screen recordings**
If applicable, add screenshots/screen recordings to help explain your problem.
![neu_windows_screen_recording](https://i.imgur.com/a8qpMnA.gif)

**NOTE**

I believe this is a **Windows 10** specific problem. I tested the same on **Linux** but no flash was seen and it worked as expected.

**Specifications**  
 - OS: Windows 10 x64
 - Neutralinojs version: [e.g. v4.6.0]
 - Neutralinojs client library version: [e.g. v3.5.0]
 - Neutralinojs CLI version: [e.g. v9.2.0]

*Note: you can enter the `neu version` command to find these details*

**Additional context**
When I launch the app I want it to stay hidden until a certain promise is resolved (here I just did the 2 second setInterval for testing purposes). The flash on Window's versions is very negatively received.

**Comment by Blatman** [comment] 2022-06-13 18:26
Just wondering - is this a duplicate of #900 ?

**Comment by Blatman** [comment] 2022-06-14 06:16
Maybe it is an idea to reference the other issue then both can be closed when problem is fixed.

**Comment by shalithasuranga** [comment] 2023-03-07 07:43
This was fixed with #1061 and will be released with the next framework release. Thank you :tada:

**Closed by shalithasuranga** 2023-03-07 07:43 UTC
Labels: bug
